apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker-controller
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: metal-load-balancer-controller
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: manager
        image: controller:latest
        command:
          - /speaker
        args:
          - --leader-elect
          - --health-probe-bind-address=:8082
          - --node-address=$NODE_IP
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8082
          initialDelaySeconds: 5
          periodSeconds: 10
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
